theme: jekyll-theme-minimal
title: Evangelos Stavropoulos-Vasilakis
description: Mechanical Engineer
logo: [https://github.com/mc08662/mc08662.github.io/blob/master/mars2016_bw02_4.jpg]
show_downloads: false
